### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Jedi-Bladel**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂

**Comment by Jedi-Bladel** [comment]
I have no idea what your talking about. I do not believe I did anything in Github so if I did I am not exactly sure how. So in order to not do it again can you identify the issue I raised. I had noticed I received a few GitHub notifications but I wasn’t sure why. The only things I did was use the Ask section, message directly with a friend, and where it says to suggest edits to the curriculum, I suggested some edits. 


> On Aug 11, 2017, at 3:08 PM, Gabe Jackson <notifications@github.com> wrote:
> 
> Hi there,
> 
> Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via a quick edit, or bugs with the Learn platform (such as lights not turning green or IDE issues).
> 
> This issue would be perfect for the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
> 
> If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).
> 
> Thanks! 🙂
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Best Regards, 
Timothy Bladel
PR Officer for the World Affairs Council of the Quad Cities
Owner and Publicity Advocate for Preeminence Publicity Advocate
(309)292-1774

**Comment by gj** [comment]
Hi there!

When you "suggest edits to the curriculum," that happens on GitHub. 🙂

**Comment by Jedi-Bladel** [comment]
Oh, ok. I can't remember which ones I suggested, but one was that the curriculum seemed unclear in its instruction, although in hindsight it may have been me just being daft and forgetting they were talking about the console in the inspect page and not IDE. Ha, my bad. I'll try to be more thoughtful.

**Comment by gj** [comment]
Not a problem either way @Jedi-Bladel ! 🙂

We just like to make sure students get routed to the help they need, and for things like this that's usually Ask a Question or the Learn Help Center. Ask a Question is also a good place to get a second opinion on whether something rises to the level of a curriculum issue or if it could be solved with some one-on-one help.

**Pull request closed without merging**
